import { QuickService } from './types'

export const DEFAULT_SERVICES: QuickService[] = [
  // ── Elétrica ──
  {
    id: '8b5c4095-e56f-4066-80c4-37f359ee47c2',
    name: 'Troca de Chuveiro / Resistência',
    category: 'Elétrica',
    description: 'Substituição de chuveiro ou resistência elétrica com teste de funcionamento e vedação.',
    fixed_price: 70.0,
    platform_fee: 12.0,
    icon: 'ShowerHead',
    color: '#F59E0B',
    sort_order: 1,
    is_active: true,
  },
  {
    id: '88b9104b-be4f-4b44-a6cf-5eff3748b60b',
    name: 'Troca de Tomada / Interruptor / Lâmpada',
    category: 'Elétrica',
    description: 'Instalação ou substituição de tomadas, interruptores e lâmpadas residenciais.',
    fixed_price: 50.0,
    platform_fee: 12.0,
    icon: 'Plug',
    color: '#F59E0B',
    sort_order: 2,
    is_active: true,
  },
  {
    id: '2a09df38-84b4-4853-bdff-338e27981930',
    name: 'Instalação de Ventilador de Teto',
    category: 'Elétrica',
    description: 'Montagem e instalação elétrica de ventilador de teto com suporte e balanceamento.',
    fixed_price: 120.0,
    platform_fee: 12.0,
    icon: 'Fan',
    color: '#F59E0B',
    sort_order: 3,
    is_active: true,
  },
  {
    id: 'c6663a89-bab1-465f-937e-a4b366350cc7',
    name: 'Instalação de Plafon / Painel LED',
    category: 'Elétrica',
    description: 'Fixação e ligação elétrica de luminárias de sobrepor ou embutir tipo plafon / LED.',
    fixed_price: 60.0,
    platform_fee: 12.0,
    icon: 'Lightbulb',
    color: '#F59E0B',
    sort_order: 4,
    is_active: true,
  },

  // ── Hidráulica ──
  {
    id: '1e6d94df-5e8d-49ec-9c1b-6d30f99b9529',
    name: 'Troca de Torneira / Sifão de Pia',
    category: 'Hidráulica',
    description: 'Substituição de torneira, flexível ou sifão de pia com fita veda-rosca e teste de estanqueidade.',
    fixed_price: 60.0,
    platform_fee: 12.0,
    icon: 'Droplet',
    color: '#06B6D4',
    sort_order: 5,
    is_active: true,
  },
  {
    id: 'f1698097-5802-4a0f-b529-5003490c2855',
    name: 'Desentupimento de Ralo / Vaso Sanitário',
    category: 'Hidráulica',
    description: 'Desobstrução rápida de encanamento de ralo, pia ou vaso sanitário com equipamento manual.',
    fixed_price: 100.0,
    platform_fee: 12.0,
    icon: 'Pipette',
    color: '#06B6D4',
    sort_order: 6,
    is_active: true,
  },
  {
    id: '4cf805b2-09f3-4ecb-8623-11a687e0ae39',
    name: 'Reparo de Caixa Acoplada',
    category: 'Hidráulica',
    description: 'Ajuste ou troca de mecanismo de entrada/saída, boia e vedação de caixa acoplada.',
    fixed_price: 70.0,
    platform_fee: 12.0,
    icon: 'Wrench',
    color: '#06B6D4',
    sort_order: 7,
    is_active: true,
  },
  {
    id: '5ed20888-b613-47e6-8ae7-83020a3c0914',
    name: 'Vedação de Box / Pia com Silicone',
    category: 'Hidráulica',
    description: 'Aplicação de silicone antifungo para vedação perfeita contra infiltração em pias e box.',
    fixed_price: 60.0,
    platform_fee: 12.0,
    icon: 'ShieldCheck',
    color: '#06B6D4',
    sort_order: 8,
    is_active: true,
  },

  // ── Montagem e Fixação ──
  {
    id: 'db0b0819-8a5a-49bc-8faa-a393c2b65cc4',
    name: 'Fixação de Suporte de TV / Cortina / Quadro',
    category: 'Montagem',
    description: 'Perfuração precisa em alvenaria e fixação segura de suporte de TV, varão de cortina ou nichos.',
    fixed_price: 70.0,
    platform_fee: 12.0,
    icon: 'Tv',
    color: '#8B5CF6',
    sort_order: 9,
    is_active: true,
  },
  {
    id: '966fea9b-d7eb-483f-9309-c971d64d2b77',
    name: 'Montagem / Desmontagem Móvel Pequeno',
    category: 'Montagem',
    description: 'Montagem de móveis avulsos como mesas de cabeceira, cadeiras de escritório, sapateiras e mesas.',
    fixed_price: 90.0,
    platform_fee: 12.0,
    icon: 'Hammer',
    color: '#8B5CF6',
    sort_order: 10,
    is_active: true,
  },
  {
    id: 'fb25cfbe-3e7c-4107-bcbe-f40124e09599',
    name: 'Instalação de Varal de Teto / Parede',
    category: 'Montagem',
    description: 'Fixação firme e alinhamento de varal articulado ou de teto com cordas e roldanas.',
    fixed_price: 80.0,
    platform_fee: 12.0,
    icon: 'Shirt',
    color: '#8B5CF6',
    sort_order: 11,
    is_active: true,
  },
  {
    id: 'bc59db09-9149-4eb8-a57c-659f195ff8d5',
    name: 'Regulagem de Dobradiças e Gavetas',
    category: 'Montagem',
    description: 'Alinhamento de portas de armários desreguladas, troca de puxadores e ajuste de trilhos de gaveta.',
    fixed_price: 60.0,
    platform_fee: 12.0,
    icon: 'Settings2',
    color: '#8B5CF6',
    sort_order: 12,
    is_active: true,
  },

  // ── Chaveiro ──
  {
    id: '15dc3813-d19e-4c09-9dc9-7690a3141a1b',
    name: 'Abertura de Porta (Bateu-Fechou)',
    category: 'Chaveiro',
    description: 'Abertura rápida e sem danos de portas residenciais trancadas acidentalmente.',
    fixed_price: 100.0,
    platform_fee: 12.0,
    icon: 'Key',
    color: '#EAB308',
    sort_order: 13,
    is_active: true,
  },
  {
    id: 'd8505766-6373-460c-acd2-34bfb0372b46',
    name: 'Troca de Fechadura / Miolo de Porta',
    category: 'Chaveiro',
    description: 'Substituição completa de fechadura de sobrepor ou miolo de cilindro para nova chave.',
    fixed_price: 80.0,
    platform_fee: 12.0,
    icon: 'Lock',
    color: '#EAB308',
    sort_order: 14,
    is_active: true,
  },

  // ── Instalação & Eletrodomésticos ──
  {
    id: '65943f94-fdd6-48a1-a3d0-ffbb6dd88def',
    name: 'Instalação de Máquina de Lavar',
    category: 'Instalação',
    description: 'Conexão hidráulica (entrada/saída de água), nivelamento dos pés e teste de centrifugação.',
    fixed_price: 70.0,
    platform_fee: 12.0,
    icon: 'WashingMachine',
    color: '#10B981',
    sort_order: 15,
    is_active: true,
  },
  {
    id: '53102e50-835e-4132-a4f3-02929e52e44b',
    name: 'Troca de Mangueira e Registro de Gás',
    category: 'Instalação',
    description: 'Troca preventiva de mangueira trançada e regulador de pressão de gás com teste de espuma de sabão.',
    fixed_price: 50.0,
    platform_fee: 12.0,
    icon: 'Flame',
    color: '#10B981',
    sort_order: 16,
    is_active: true,
  },
]
