import { QuickService } from './types'

export const DEFAULT_SERVICES: QuickService[] = [
  // ── Elétrica ──
  {
    id: '1',
    name: 'Troca de Chuveiro / Resistência',
    category: 'Elétrica',
    description: 'Substituição de chuveiro ou resistência elétrica com teste de funcionamento e vedação.',
    fixed_price: 70.0,
    platform_fee: 12.0,
    icon: 'ShowerHead',
    color: '#F59E0B',
    sort_order: 1,
    is_active: true,
  },
  {
    id: '2',
    name: 'Troca de Tomada / Interruptor / Lâmpada',
    category: 'Elétrica',
    description: 'Instalação ou substituição de tomadas, interruptores e lâmpadas residenciais.',
    fixed_price: 50.0,
    platform_fee: 12.0,
    icon: 'Plug',
    color: '#F59E0B',
    sort_order: 2,
    is_active: true,
  },
  {
    id: '3',
    name: 'Instalação de Ventilador de Teto',
    category: 'Elétrica',
    description: 'Montagem e instalação elétrica de ventilador de teto com suporte e balanceamento.',
    fixed_price: 120.0,
    platform_fee: 12.0,
    icon: 'Fan',
    color: '#F59E0B',
    sort_order: 3,
    is_active: true,
  },
  {
    id: '4',
    name: 'Instalação de Plafon / Painel LED',
    category: 'Elétrica',
    description: 'Fixação e ligação elétrica de luminárias de sobrepor ou embutir tipo plafon / LED.',
    fixed_price: 60.0,
    platform_fee: 12.0,
    icon: 'Lightbulb',
    color: '#F59E0B',
    sort_order: 4,
    is_active: true,
  },

  // ── Hidráulica ──
  {
    id: '5',
    name: 'Troca de Torneira / Sifão de Pia',
    category: 'Hidráulica',
    description: 'Substituição de torneira, flexível ou sifão de pia com fita veda-rosca e teste de estanqueidade.',
    fixed_price: 60.0,
    platform_fee: 12.0,
    icon: 'Droplet',
    color: '#06B6D4',
    sort_order: 5,
    is_active: true,
  },
  {
    id: '6',
    name: 'Desentupimento de Ralo / Vaso Sanitário',
    category: 'Hidráulica',
    description: 'Desobstrução mecânica ágil de ralos de banheiro, pias e vasos sanitários.',
    fixed_price: 100.0,
    platform_fee: 12.0,
    icon: 'Pipette',
    color: '#06B6D4',
    sort_order: 6,
    is_active: true,
  },
  {
    id: '7',
    name: 'Reparo de Caixa Acoplada',
    category: 'Hidráulica',
    description: 'Regulagem ou troca de mecanismo de entrada/saída e boia da caixa acoplada.',
    fixed_price: 70.0,
    platform_fee: 12.0,
    icon: 'Wrench',
    color: '#06B6D4',
    sort_order: 7,
    is_active: true,
  },
  {
    id: '8',
    name: 'Vedação de Box / Pia com Silicone',
    category: 'Hidráulica',
    description: 'Aplicação e acabamento profissional de silicone antifungo em box de banheiro ou pias.',
    fixed_price: 60.0,
    platform_fee: 12.0,
    icon: 'ShieldCheck',
    color: '#06B6D4',
    sort_order: 8,
    is_active: true,
  },

  // ── Montagem & Fixação ──
  {
    id: '9',
    name: 'Fixação de Suporte de TV / Cortina / Quadro',
    category: 'Montagem',
    description: 'Instalação com nível de bolha de suportes de TV, varões de cortina, espelhos e prateleiras.',
    fixed_price: 70.0,
    platform_fee: 12.0,
    icon: 'Tv',
    color: '#8B5CF6',
    sort_order: 9,
    is_active: true,
  },
  {
    id: '10',
    name: 'Montagem / Desmontagem Móvel Pequeno',
    category: 'Montagem',
    description: 'Montagem ou desmontagem rápida de móveis avulsos, criados-mudos, estantes e berços.',
    fixed_price: 90.0,
    platform_fee: 12.0,
    icon: 'Hammer',
    color: '#8B5CF6',
    sort_order: 10,
    is_active: true,
  },
  {
    id: '11',
    name: 'Instalação de Varal de Teto / Parede',
    category: 'Montagem',
    description: 'Furação e fixação com buchas adequadas para varais retráteis ou de roldana.',
    fixed_price: 80.0,
    platform_fee: 12.0,
    icon: 'Shirt',
    color: '#8B5CF6',
    sort_order: 11,
    is_active: true,
  },
  {
    id: '12',
    name: 'Regulagem de Dobradiças e Gavetas',
    category: 'Montagem',
    description: 'Alinhamento e ajuste de portas de armários, corrediças e gavetas emperradas.',
    fixed_price: 60.0,
    platform_fee: 12.0,
    icon: 'Settings2',
    color: '#8B5CF6',
    sort_order: 12,
    is_active: true,
  },

  // ── Chaveiro & Segurança ──
  {
    id: '13',
    name: 'Abertura de Porta (Bateu-Fechou)',
    category: 'Chaveiro',
    description: 'Abertura técnica emergencial de portas residenciais trancadas sem chave.',
    fixed_price: 100.0,
    platform_fee: 12.0,
    icon: 'Key',
    color: '#EAB308',
    sort_order: 13,
    is_active: true,
  },
  {
    id: '14',
    name: 'Troca de Fechadura / Miolo de Porta',
    category: 'Chaveiro',
    description: 'Substituição completa de fechadura de sobrepor/embutir ou troca do cilindro (miolo).',
    fixed_price: 80.0,
    platform_fee: 12.0,
    icon: 'Lock',
    color: '#EAB308',
    sort_order: 14,
    is_active: true,
  },

  // ── Instalação & Eletro ──
  {
    id: '15',
    name: 'Instalação de Máquina de Lavar',
    category: 'Instalação',
    description: 'Conexão hidráulica de entrada e saída, nivelamento dos pés e teste operacional.',
    fixed_price: 70.0,
    platform_fee: 12.0,
    icon: 'WashingMachine',
    color: '#10B981',
    sort_order: 15,
    is_active: true,
  },
  {
    id: '16',
    name: 'Troca de Mangueira e Registro de Gás',
    category: 'Instalação',
    description: 'Substituição preventiva ou corretiva de mangueira metálica/flexível e válvula de botijão.',
    fixed_price: 50.0,
    platform_fee: 12.0,
    icon: 'Flame',
    color: '#10B981',
    sort_order: 16,
    is_active: true,
  },
]
