import { QuickService } from './types'

export const DEFAULT_SERVICES: QuickService[] = [
  {
    id: '1',
    name: 'Troca de Chuveiro / Resistência',
    category: 'Elétrica',
    description: 'Substituição de chuveiro ou resistência elétrica com teste de funcionamento.',
    fixed_price: 70.0,
    platform_fee: 10.0,
    icon: 'zap',
    color: '#6366F1',
    sort_order: 1,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Troca de Tomada / Interruptor / Lâmpada',
    category: 'Elétrica',
    description: 'Instalação ou substituição de tomadas, interruptores e lâmpadas residenciais.',
    fixed_price: 50.0,
    platform_fee: 10.0,
    icon: 'plug',
    color: '#6366F1',
    sort_order: 2,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: '3',
    name: 'Instalação de Ventilador de Teto',
    category: 'Elétrica',
    description: 'Montagem e instalação elétrica de ventilador de teto com suporte.',
    fixed_price: 120.0,
    platform_fee: 15.0,
    icon: 'wind',
    color: '#6366F1',
    sort_order: 3,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: '4',
    name: 'Troca de Torneira / Sifão de Pia',
    category: 'Hidráulica',
    description: 'Substituição de torneira ou sifão com vedação e teste de estanqueidade.',
    fixed_price: 60.0,
    platform_fee: 10.0,
    icon: 'droplets',
    color: '#06B6D4',
    sort_order: 4,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: '5',
    name: 'Desentupimento Ralo / Vaso Sanitário',
    category: 'Hidráulica',
    description: 'Desentupimento mecânico de ralos, pias e vasos sanitários.',
    fixed_price: 100.0,
    platform_fee: 15.0,
    icon: 'waves',
    color: '#06B6D4',
    sort_order: 5,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: '6',
    name: 'Fixação de Suporte TV / Cortina / Quadro',
    category: 'Montagem',
    description: 'Instalação de suportes, varões de cortina e quadros com furação adequada.',
    fixed_price: 70.0,
    platform_fee: 10.0,
    icon: 'tv-2',
    color: '#F59E0B',
    sort_order: 6,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: '7',
    name: 'Montagem / Desmontagem Móvel Pequeno',
    category: 'Montagem',
    description: 'Montagem ou desmontagem de estantes, gaveteiros, berços e móveis pequenos.',
    fixed_price: 90.0,
    platform_fee: 10.0,
    icon: 'package',
    color: '#F59E0B',
    sort_order: 7,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: '8',
    name: 'Visita Diagnóstico / Socorro Geral 24h',
    category: 'Emergência',
    description: 'Visita emergencial para diagnóstico e primeiros reparos. Disponível 24 horas.',
    fixed_price: 50.0,
    platform_fee: 10.0,
    icon: 'ambulance',
    color: '#EF4444',
    sort_order: 8,
    is_active: true,
  },
  {
    id: '9',
    name: 'Pintura de Parede / Retoque de Tinta',
    category: 'Pintura',
    description: 'Pintura, emassamento e retoques residenciais com acabamento profissional.',
    fixed_price: 110.0,
    platform_fee: 15.0,
    icon: 'paint-bucket',
    color: '#8B5CF6',
    sort_order: 9,
    is_active: true,
  },
  {
    id: '10',
    name: 'Troca de Fechadura / Ajuste de Porta',
    category: 'Pequenos Reparos',
    description: 'Instalação ou troca de fechaduras, trincos, dobradiças e ajustes de portas.',
    fixed_price: 75.0,
    platform_fee: 10.0,
    icon: 'hammer',
    color: '#F59E0B',
    sort_order: 10,
    is_active: true,
  },
]
